// Generated by Tools/generate-lucide-assets.ts from lucide-react 1.27.0 (ISC).
// Do not edit this file directly.

import SwiftUI

enum LucideIcon: String, CaseIterable, Sendable {
  case archive = "LucideArchive"
  case arrowDown = "LucideArrowDown"
  case arrowLeft = "LucideArrowLeft"
  case arrowRight = "LucideArrowRight"
  case arrowUp = "LucideArrowUp"
  case bookOpen = "LucideBookOpen"
  case brain = "LucideBrain"
  case check = "LucideCheck"
  case checkCheck = "LucideCheckCheck"
  case circleCheck = "LucideCircleCheck"
  case chevronDown = "LucideChevronDown"
  case chevronRight = "LucideChevronRight"
  case chevronUp = "LucideChevronUp"
  case circle = "LucideCircle"
  case circleAlert = "LucideCircleAlert"
  case circleQuestion = "LucideCircleQuestion"
  case circleX = "LucideCircleX"
  case clipboardPaste = "LucideClipboardPaste"
  case clock = "LucideClock"
  case copy = "LucideCopy"
  case cornerDownLeft = "LucideCornerDownLeft"
  case cornerDownRight = "LucideCornerDownRight"
  case database = "LucideDatabase"
  case ellipsis = "LucideEllipsis"
  case file = "LucideFile"
  case fileArchive = "LucideFileArchive"
  case fileDiff = "LucideFileDiff"
  case filePen = "LucideFilePen"
  case fileText = "LucideFileText"
  case folder = "LucideFolder"
  case folderPen = "LucideFolderPen"
  case folderSearch = "LucideFolderSearch"
  case gitBranch = "LucideGitBranch"
  case gitFork = "LucideGitFork"
  case hardDrive = "LucideHardDrive"
  case history = "LucideHistory"
  case house = "LucideHouse"
  case image = "LucideImage"
  case images = "LucideImages"
  case info = "LucideInfo"
  case keyboard = "LucideKeyboard"
  case keyRound = "LucideKeyRound"
  case laptop = "LucideLaptop"
  case laptopMinimal = "LucideLaptopMinimal"
  case link = "LucideLink"
  case listChecks = "LucideListChecks"
  case loader = "LucideLoader"
  case lockKeyhole = "LucideLockKeyhole"
  case messagesSquare = "LucideMessagesSquare"
  case monitor = "LucideMonitor"
  case monitorSmartphone = "LucideMonitorSmartphone"
  case monitorX = "LucideMonitorX"
  case network = "LucideNetwork"
  case palette = "LucidePalette"
  case plus = "LucidePlus"
  case qrCode = "LucideQrCode"
  case refreshCw = "LucideRefreshCw"
  case rotateCcw = "LucideRotateCcw"
  case search = "LucideSearch"
  case server = "LucideServer"
  case settings = "LucideSettings"
  case shieldAlert = "LucideShieldAlert"
  case shieldCheck = "LucideShieldCheck"
  case slidersHorizontal = "LucideSlidersHorizontal"
  case square = "LucideSquare"
  case squarePen = "LucideSquarePen"
  case squareTerminal = "LucideSquareTerminal"
  case trash = "LucideTrash"
  case triangleAlert = "LucideTriangleAlert"
  case undo = "LucideUndo"
  case userCog = "LucideUserCog"
  case vibrate = "LucideVibrate"
  case wifi = "LucideWifi"
  case wifiOff = "LucideWifiOff"
  case wrench = "LucideWrench"
  case x = "LucideX"
  case zap = "LucideZap"
  case squareFilled = "LucideSquareFilled"

  var assetName: String { rawValue }
}

struct LucideIconView: View {
  let icon: LucideIcon
  var size: CGFloat

  init(_ icon: LucideIcon, size: CGFloat = 16) {
    self.icon = icon
    self.size = size
  }

  var body: some View {
    Image(icon.assetName)
      .resizable()
      .renderingMode(.template)
      .scaledToFit()
      .frame(
        width: HarnessIconMetrics.renderedSize(size),
        height: HarnessIconMetrics.renderedSize(size)
      )
      .frame(width: size, height: size)
      .accessibilityHidden(true)
  }
}
