import type { DynamicImportLanguageRegistration, LanguageRegistration } from 'shiki/core'

/**
 * Grammars the app ships. Each entry stays its own lazy chunk and is fetched the
 * first time a code block or diff asks for it. Shiki's full catalog is ~235
 * grammars (7.7 MB raw); this set covers what coding agents and repositories
 * actually produce at under half that.
 */
const grammars = {
  astro: () => import('@shikijs/langs/astro'),
  bat: () => import('@shikijs/langs/bat'),
  c: () => import('@shikijs/langs/c'),
  clojure: () => import('@shikijs/langs/clojure'),
  cmake: () => import('@shikijs/langs/cmake'),
  cpp: () => import('@shikijs/langs/cpp'),
  csharp: () => import('@shikijs/langs/csharp'),
  css: () => import('@shikijs/langs/css'),
  csv: () => import('@shikijs/langs/csv'),
  dart: () => import('@shikijs/langs/dart'),
  diff: () => import('@shikijs/langs/diff'),
  docker: () => import('@shikijs/langs/docker'),
  dotenv: () => import('@shikijs/langs/dotenv'),
  elixir: () => import('@shikijs/langs/elixir'),
  elm: () => import('@shikijs/langs/elm'),
  erlang: () => import('@shikijs/langs/erlang'),
  fish: () => import('@shikijs/langs/fish'),
  fsharp: () => import('@shikijs/langs/fsharp'),
  'git-commit': () => import('@shikijs/langs/git-commit'),
  'git-rebase': () => import('@shikijs/langs/git-rebase'),
  glsl: () => import('@shikijs/langs/glsl'),
  go: () => import('@shikijs/langs/go'),
  graphql: () => import('@shikijs/langs/graphql'),
  groovy: () => import('@shikijs/langs/groovy'),
  haml: () => import('@shikijs/langs/haml'),
  haskell: () => import('@shikijs/langs/haskell'),
  hcl: () => import('@shikijs/langs/hcl'),
  html: () => import('@shikijs/langs/html'),
  http: () => import('@shikijs/langs/http'),
  ini: () => import('@shikijs/langs/ini'),
  java: () => import('@shikijs/langs/java'),
  javascript: () => import('@shikijs/langs/javascript'),
  json: () => import('@shikijs/langs/json'),
  json5: () => import('@shikijs/langs/json5'),
  jsonc: () => import('@shikijs/langs/jsonc'),
  jsonl: () => import('@shikijs/langs/jsonl'),
  jsx: () => import('@shikijs/langs/jsx'),
  julia: () => import('@shikijs/langs/julia'),
  kotlin: () => import('@shikijs/langs/kotlin'),
  less: () => import('@shikijs/langs/less'),
  log: () => import('@shikijs/langs/log'),
  lua: () => import('@shikijs/langs/lua'),
  make: () => import('@shikijs/langs/make'),
  markdown: () => import('@shikijs/langs/markdown'),
  mdx: () => import('@shikijs/langs/mdx'),
  nginx: () => import('@shikijs/langs/nginx'),
  nix: () => import('@shikijs/langs/nix'),
  'objective-c': () => import('@shikijs/langs/objective-c'),
  ocaml: () => import('@shikijs/langs/ocaml'),
  perl: () => import('@shikijs/langs/perl'),
  php: () => import('@shikijs/langs/php'),
  postcss: () => import('@shikijs/langs/postcss'),
  powershell: () => import('@shikijs/langs/powershell'),
  prisma: () => import('@shikijs/langs/prisma'),
  proto: () => import('@shikijs/langs/proto'),
  python: () => import('@shikijs/langs/python'),
  r: () => import('@shikijs/langs/r'),
  regexp: () => import('@shikijs/langs/regexp'),
  ruby: () => import('@shikijs/langs/ruby'),
  rust: () => import('@shikijs/langs/rust'),
  sass: () => import('@shikijs/langs/sass'),
  scala: () => import('@shikijs/langs/scala'),
  scss: () => import('@shikijs/langs/scss'),
  shellscript: () => import('@shikijs/langs/shellscript'),
  shellsession: () => import('@shikijs/langs/shellsession'),
  sql: () => import('@shikijs/langs/sql'),
  svelte: () => import('@shikijs/langs/svelte'),
  swift: () => import('@shikijs/langs/swift'),
  terraform: () => import('@shikijs/langs/terraform'),
  toml: () => import('@shikijs/langs/toml'),
  tsx: () => import('@shikijs/langs/tsx'),
  typescript: () => import('@shikijs/langs/typescript'),
  vue: () => import('@shikijs/langs/vue'),
  wasm: () => import('@shikijs/langs/wasm'),
  xml: () => import('@shikijs/langs/xml'),
  yaml: () => import('@shikijs/langs/yaml'),
  zig: () => import('@shikijs/langs/zig'),
} satisfies Record<string, DynamicImportLanguageRegistration>

export type ShippedLanguage = keyof typeof grammars

export const shippedLanguageNames = Object.keys(grammars) as ShippedLanguage[]

/** Shiki's aliases for the shipped grammars, so `ts`, `sh` and `yml` keep working. */
export const languageAliases = {
  bash: 'shellscript',
  batch: 'bat',
  'c#': 'csharp',
  'c++': 'cpp',
  cjs: 'javascript',
  clj: 'clojure',
  console: 'shellsession',
  cs: 'csharp',
  cts: 'typescript',
  dockerfile: 'docker',
  erl: 'erlang',
  'f#': 'fsharp',
  fs: 'fsharp',
  gql: 'graphql',
  hs: 'haskell',
  jl: 'julia',
  js: 'javascript',
  kt: 'kotlin',
  kts: 'kotlin',
  makefile: 'make',
  md: 'markdown',
  mjs: 'javascript',
  mts: 'typescript',
  objc: 'objective-c',
  properties: 'ini',
  protobuf: 'proto',
  ps: 'powershell',
  ps1: 'powershell',
  py: 'python',
  rb: 'ruby',
  regex: 'regexp',
  rs: 'rust',
  sh: 'shellscript',
  shell: 'shellscript',
  tf: 'terraform',
  tfvars: 'terraform',
  ts: 'typescript',
  yml: 'yaml',
  zsh: 'shellscript',
} satisfies Record<string, ShippedLanguage>

/**
 * Every other id and alias in Shiki's catalog. These resolve to a grammar with
 * no rules, so a `.el` file in a diff or an ```elisp fence renders as plain text
 * instead of failing to resolve. `shiki-languages.test.ts` keeps the three lists
 * in sync with the installed Shiki version.
 */
export const plainLanguages: readonly string[] = [
  '1c',
  '1c-query',
  'abap',
  'actionscript-3',
  'ada',
  'adoc',
  'angular-html',
  'angular-ts',
  'apache',
  'apex',
  'apl',
  'applescript',
  'ara',
  'asciidoc',
  'asm',
  'awk',
  'ballerina',
  'be',
  'beancount',
  'berry',
  'bibtex',
  'bicep',
  'bird',
  'bird2',
  'blade',
  'bsl',
  'c3',
  'cadence',
  'cairo',
  'cdc',
  'clarity',
  'closure-templates',
  'cmd',
  'cobol',
  'codeowners',
  'codeql',
  'coffee',
  'coffeescript',
  'common-lisp',
  'coq',
  'cql',
  'crystal',
  'cue',
  'cypher',
  'd',
  'dax',
  'desktop',
  'dream-maker',
  'edge',
  'elisp',
  'emacs-lisp',
  'erb',
  'f',
  'f03',
  'f08',
  'f18',
  'f77',
  'f90',
  'f95',
  'fennel',
  'fluent',
  'for',
  'fortran-fixed-form',
  'fortran-free-form',
  'fsl',
  'ftl',
  'gd',
  'gdresource',
  'gdscript',
  'gdshader',
  'genie',
  'gherkin',
  'gjs',
  'gleam',
  'glimmer-js',
  'glimmer-ts',
  'gn',
  'gnuplot',
  'gts',
  'hack',
  'handlebars',
  'haxe',
  'hbs',
  'hjson',
  'hlsl',
  'html-derivative',
  'hurl',
  'hxml',
  'hy',
  'imba',
  'jade',
  'jinja',
  'jison',
  'jsonnet',
  'jssm',
  'just',
  'kdl',
  'kql',
  'kusto',
  'latex',
  'lean',
  'lean4',
  'liquid',
  'lisp',
  'lit',
  'llvm',
  'logo',
  'luau',
  'marko',
  'matlab',
  'mbt',
  'mbti',
  'mdc',
  'mediawiki',
  'mermaid',
  'mips',
  'mipsasm',
  'mmd',
  'mojo',
  'moonbit',
  'move',
  'nar',
  'narrat',
  'nextflow',
  'nextflow-groovy',
  'nf',
  'nim',
  'nu',
  'nushell',
  'objective-cpp',
  'odin',
  'openscad',
  'pascal',
  'perl6',
  'pkl',
  'plsql',
  'po',
  'polar',
  'pot',
  'potx',
  'powerquery',
  'prolog',
  'pug',
  'puppet',
  'purescript',
  'ql',
  'qml',
  'qmldir',
  'qss',
  'racket',
  'raku',
  'razor',
  'reg',
  'rel',
  'riscv',
  'ron',
  'rosmsg',
  'rst',
  'sas',
  'scad',
  'scheme',
  'sdbl',
  'shader',
  'shaderlab',
  'smalltalk',
  'solidity',
  'soy',
  'sparql',
  'spl',
  'splunk',
  'ssh-config',
  'stata',
  'styl',
  'stylus',
  'surql',
  'surrealql',
  'system-verilog',
  'systemd',
  'talon',
  'talonscript',
  'tasl',
  'tcl',
  'templ',
  'tex',
  'tres',
  'ts-tags',
  'tscn',
  'tsp',
  'tsv',
  'turtle',
  'twig',
  'typ',
  'typespec',
  'typst',
  'v',
  'vala',
  'vb',
  'verilog',
  'vhdl',
  'vim',
  'viml',
  'vimscript',
  'vue-html',
  'vue-vine',
  'vy',
  'vyper',
  'wenyan',
  'wgsl',
  'wiki',
  'wikitext',
  'wit',
  'wl',
  'wolfram',
  'xsl',
  'zenscript',
  '文言',
]

function plainGrammar(name: string): DynamicImportLanguageRegistration {
  const registration: LanguageRegistration = {
    name,
    scopeName: `source.${name}`,
    patterns: [],
    repository: {},
  }
  return () => Promise.resolve({ default: [registration] })
}

export const bundledLanguages = {
  ...Object.fromEntries(plainLanguages.map((name) => [name, plainGrammar(name)] as const)),
  ...grammars,
  ...Object.fromEntries(
    Object.entries(languageAliases).map(([alias, target]) => [alias, grammars[target]] as const),
  ),
} satisfies Record<string, DynamicImportLanguageRegistration>

export type BundledLanguage = keyof typeof bundledLanguages & string
